version: '3'
services:
  ubuntu-container:
    image: ubuntu:latest
    ports:
      - "2222:22"
    networks:
      - my_network
    command: bash -c "apt-get update && apt-get install -y openssh-server && service ssh restart && useradd -m -d /home/mansouriamen -s /bin/bash mansouriamen && echo 'mansouriamen:password' | chpasswd && tail -f /dev/null"

  ansible-container:
    image: alpinelinux/ansible:latest
    volumes:
      - ./ansible:/ansible
    networks:
      - my_network
    command: apk update && apk add sshpass && tail -f /dev/null

networks:
  my_network:
